/**
 * @file audio_ipc.h
 * @brief Inter-Processor Communication for LC3 Audio Frames
 *
 * This module provides IPC between CM33 and CM55 cores for transferring
 * LC3 encoded audio frames:
 *   - TX Path: CM55 (LC3 encode) -> CM33 (ISOC TX)
 *   - RX Path: CM33 (ISOC RX) -> CM55 (LC3 decode)
 *
 * Uses Infineon's mtb-ipc library for thread-safe, interrupt-safe
 * communication between cores.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef AUDIO_IPC_H
#define AUDIO_IPC_H

#include <stdint.h>
#include <stdbool.h>
#include "cy_result.h"

#ifdef __cplusplus
extern "C" {
#endif

/*******************************************************************************
 * Constants
 ******************************************************************************/

/** Maximum LC3 frame size in bytes (155 bytes for 48kHz/10ms at highest bitrate) */
#define AUDIO_IPC_MAX_LC3_FRAME_SIZE    (155U)

/** Number of frames in each IPC queue */
#define AUDIO_IPC_QUEUE_DEPTH           (8U)

/** IPC channel identifiers */
#define AUDIO_IPC_CHANNEL_LC3_TX        (0U)  /**< CM55 -> CM33 (encoded frames for ISOC TX) */
#define AUDIO_IPC_CHANNEL_LC3_RX        (1U)  /**< CM33 -> CM55 (received frames for decode) */

/*******************************************************************************
 * Data Types
 ******************************************************************************/

/**
 * @brief LC3 audio frame for IPC transfer
 *
 * This structure is placed in shared memory and transferred between cores.
 * Must be cache-aligned on systems with data cache.
 */
typedef struct __attribute__((aligned(32))) {
    uint8_t  data[AUDIO_IPC_MAX_LC3_FRAME_SIZE];  /**< LC3 encoded data */
    uint16_t length;                               /**< Actual frame length */
    uint16_t sequence;                             /**< Sequence number for sync */
    uint32_t timestamp;                            /**< Timestamp in microseconds */
    uint8_t  flags;                                /**< Frame flags (see AUDIO_IPC_FLAG_*) */
    uint8_t  reserved[3];                          /**< Padding for alignment */
} audio_ipc_frame_t;

/** Frame flags */
#define AUDIO_IPC_FLAG_VALID        (0x01U)  /**< Frame contains valid data */
#define AUDIO_IPC_FLAG_PLC          (0x02U)  /**< Frame was generated by PLC */
#define AUDIO_IPC_FLAG_SILENCE      (0x04U)  /**< Frame contains silence */

/**
 * @brief IPC statistics
 */
typedef struct {
    uint32_t tx_frames;           /**< Frames sent to other core */
    uint32_t rx_frames;           /**< Frames received from other core */
    uint32_t tx_queue_full;       /**< TX queue full events (dropped frames) */
    uint32_t rx_queue_empty;      /**< RX queue empty events (underruns) */
    uint32_t errors;              /**< IPC errors */
} audio_ipc_stats_t;

/**
 * @brief Callback for received frames
 *
 * @param frame     Pointer to received frame
 * @param user_data User context
 */
typedef void (*audio_ipc_rx_callback_t)(const audio_ipc_frame_t *frame, void *user_data);

/*******************************************************************************
 * API Functions - CM33 (Primary Core)
 ******************************************************************************/

/**
 * @brief Initialize IPC on CM33 (primary core)
 *
 * Must be called before CM55 boots or calls audio_ipc_init_secondary().
 * Creates and initializes IPC queues for LC3 frame transfer.
 *
 * @return CY_RSLT_SUCCESS on success
 */
cy_rslt_t audio_ipc_init_primary(void);

/**
 * @brief Send LC3 frame to CM55 for decoding (CM33 -> CM55)
 *
 * Called by ISOC handler when LC3 data is received over BLE.
 * Non-blocking; returns immediately if queue is full.
 *
 * @param frame     LC3 frame to send
 * @return CY_RSLT_SUCCESS on success, error if queue full
 */
cy_rslt_t audio_ipc_send_to_decoder(const audio_ipc_frame_t *frame);

/**
 * @brief Receive LC3 frame from CM55 encoder (CM55 -> CM33)
 *
 * Called by ISOC handler to get encoded LC3 data for BLE transmission.
 * Non-blocking; returns immediately if no frame available.
 *
 * @param frame     Buffer to receive LC3 frame
 * @return CY_RSLT_SUCCESS on success, error if queue empty
 */
cy_rslt_t audio_ipc_receive_from_encoder(audio_ipc_frame_t *frame);

/**
 * @brief Check if encoded frames are available (CM55 -> CM33)
 *
 * @return Number of frames available in the queue
 */
uint32_t audio_ipc_encoder_frames_available(void);

/*******************************************************************************
 * API Functions - CM55 (Secondary Core)
 ******************************************************************************/

/**
 * @brief Initialize IPC on CM55 (secondary core)
 *
 * Must be called after CM33 has called audio_ipc_init_primary().
 * Gets handles to existing IPC queues.
 *
 * @return CY_RSLT_SUCCESS on success
 */
cy_rslt_t audio_ipc_init_secondary(void);

/**
 * @brief Send encoded LC3 frame to CM33 for ISOC TX (CM55 -> CM33)
 *
 * Called by audio task after encoding PCM to LC3.
 * Non-blocking; returns immediately if queue is full.
 *
 * @param frame     Encoded LC3 frame to send
 * @return CY_RSLT_SUCCESS on success, error if queue full
 */
cy_rslt_t audio_ipc_send_encoded_frame(const audio_ipc_frame_t *frame);

/**
 * @brief Receive LC3 frame from CM33 for decoding (CM33 -> CM55)
 *
 * Called by audio task to get LC3 data for decoding.
 * Non-blocking; returns immediately if no frame available.
 *
 * @param frame     Buffer to receive LC3 frame
 * @return CY_RSLT_SUCCESS on success, error if queue empty
 */
cy_rslt_t audio_ipc_receive_for_decode(audio_ipc_frame_t *frame);

/**
 * @brief Check if frames are available for decoding (CM33 -> CM55)
 *
 * @return Number of frames available in the queue
 */
uint32_t audio_ipc_decoder_frames_available(void);

/**
 * @brief Register callback for received frames (CM55 side)
 *
 * Optional: If registered, callback is invoked from IPC interrupt
 * when new frames arrive from CM33.
 *
 * @param callback  Callback function (NULL to disable)
 * @param user_data User context passed to callback
 * @return CY_RSLT_SUCCESS on success
 */
cy_rslt_t audio_ipc_register_rx_callback(audio_ipc_rx_callback_t callback, void *user_data);

/*******************************************************************************
 * API Functions - Common
 ******************************************************************************/

/**
 * @brief Get IPC statistics
 *
 * @param stats     Buffer to receive statistics
 * @return CY_RSLT_SUCCESS on success
 */
cy_rslt_t audio_ipc_get_stats(audio_ipc_stats_t *stats);

/**
 * @brief Reset IPC statistics
 */
void audio_ipc_reset_stats(void);

/**
 * @brief Check if IPC is initialized and ready
 *
 * @return true if IPC is initialized
 */
bool audio_ipc_is_ready(void);

/**
 * @brief Deinitialize IPC
 *
 * Releases IPC resources. Should be called during shutdown.
 */
void audio_ipc_deinit(void);

#ifdef __cplusplus
}
#endif

#endif /* AUDIO_IPC_H */
