/*******************************************************************************
* File Name: gatt.h
*
* Description: This file is the public interface of gatt.c
*
* Related Document: See README.md
*
********************************************************************************
* (c) 2024-2025, Infineon Technologies AG, or an affiliate of Infineon Technologies AG. All rights reserved.
* This software, associated documentation and materials ("Software") is owned by
* Infineon Technologies AG or one of its affiliates ("Infineon") and is protected
* by and subject to worldwide patent protection, worldwide copyright laws, and
* international treaty provisions. Therefore, you may use this Software only as
* provided in the license agreement accompanying the software package from which
* you obtained this Software. If no license agreement applies, then any use,
* reproduction, modification, translation, or compilation of this Software is
* prohibited without the express written permission of Infineon.
* Disclaimer: UNLESS OTHERWISE EXPRESSLY AGREED WITH INFINEON, THIS SOFTWARE
* IS PROVIDED AS-IS, WITH NO WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING,
* BUT NOT LIMITED TO, ALL WARRANTIES OF NON-INFRINGEMENT OF THIRD-PARTY RIGHTS AND
* IMPLIED WARRANTIES SUCH AS WARRANTIES OF FITNESS FOR A SPECIFIC USE/PURPOSE OR
* MERCHANTABILITY. Infineon reserves the right to make changes to the Software
* without notice. You are responsible for properly designing, programming, and
* testing the functionality and safety of your intended application of the
* Software, as well as complying with any legal requirements related to its
* use. Infineon does not guarantee that the Software will be free from intrusion,
* data theft or loss, or other breaches ("Security Breaches"), and Infineon
* shall have no liability arising out of any Security Breaches. Unless otherwise
* explicitly approved by Infineon, the Software may not be used in any application
* where a failure of the Product or any consequences of the use thereof can
* reasonably be expected to result in personal injury.
*******************************************************************************/
#ifndef APP_GATTS_H__
#define APP_GATTS_H__

/*******************************************************************************
* Includes
*******************************************************************************/
#include "wiced_bt_gatt.h"
#include "wiced_bt_ble.h"
#include "cycfg_gatt_db.h"  /* generated by BT configurator */

/*******************************************************************************
* Function Declarations
*******************************************************************************/
 wiced_bt_gatt_status_t gatt_read_req_default_handler( uint16_t conn_id,
 wiced_bt_gatt_read_t *p_req,wiced_bt_gatt_opcode_t opcode,
 uint16_t len_requested );
 wiced_bt_gatt_status_t gatt_write_default_handler(uint16_t conn_id,
         wiced_bt_gatt_write_req_t * p_wr_data);
 wiced_bt_gatt_status_t gatt_initialize(void);
const gatt_db_lookup_table_t * wiced_bt_util_get_attribute
(gatt_db_lookup_table_t * p_attribute, uint16_t handle);

#endif //APP_GATTS_H__
